// font5x8.h — GENERATED by tools/genfont.py, do not edit.
//
// Source: X11 misc-fixed 5x8 (public domain). ASCII 0x20..0x7E only; this
// drives the 8-pixel status strip below the terminal grid.
#pragma once

#include <stdint.h>

#define STATUS_FONT_W 5
#define STATUS_FONT_H 8
#define STATUS_FONT_FIRST 0x20
#define STATUS_FONT_LAST  0x7E
#define STATUS_FONT_COUNT 95

extern const uint8_t font5x8_ascii[STATUS_FONT_COUNT * STATUS_FONT_H];
