// font6x13.h — GENERATED by tools/genfont.py, do not edit.
//
// Source: X11 misc-fixed 6x13 / 6x13B (public domain), vendored in
// tools/fonts/. Regenerate with:  python3 tools/genfont.py
//
// One byte per pixel row, 13 rows per glyph, pixels MSB-aligned (bit 7 is the
// leftmost of the 6 columns; bits 1..0 are always zero). Glyph 0 is the
// "unmapped codepoint" box — deliberately not a '?', so a font gap is visibly
// different from an encoding bug.
#pragma once

#include <stdint.h>

#define FONT_CELL_W 6
#define FONT_CELL_H 13
#define FONT6X13_GLYPH_COUNT 2016

// The data lives in font6x13.c so that both the renderer and the on-screen
// keyboard can use it without duplicating 51 KB of flash.
extern const uint8_t font6x13_regular[FONT6X13_GLYPH_COUNT * FONT_CELL_H];
extern const uint8_t font6x13_bold[FONT6X13_GLYPH_COUNT * FONT_CELL_H];

typedef struct {
    uint16_t lo, hi, base;
} glyph_range_t;

// Ascending and non-overlapping, which is what lets the lookup in glyph.c stop
// early and cache the last hit.
extern const glyph_range_t font6x13_ranges[];
#define FONT6X13_RANGE_COUNT 15
